using System.Collections.Generic;
using AVA.UPS.Adapter.Models;
using AVA.UPS.Adapter.Validation;

namespace AVA.UPS.Adapter.Dispatcher
{
    /// <summary>
    /// Represents the result of a UPS dispatch operation.
    /// Includes structured diagnostics, mismatch reporting,
    /// and correlation-aware metadata for UPS v1.0+ routing.
    /// </summary>
    public class DispatcherResult
    {
        /// <summary>
        /// True if the dispatch operation completed successfully.
        /// </summary>
        public bool Success { get; set; }

        /// <summary>
        /// The UParam payload returned by the invoked method or error handler.
        /// Always non-null.
        /// </summary>
        public List<UParam> Payload { get; set; } = new();

        /// <summary>
        /// Optional error type (e.g., ContractError, InvocationError, AdapterError).
        /// Useful for diagnostics, logging, and multi-agent UPS routing.
        /// </summary>
        public string? ErrorType { get; set; }

        /// <summary>
        /// Detailed mismatch entries generated by contract validation
        /// or adapter-level type coercion reporting.
        /// </summary>
        public List<ContractMismatchDetail>? Mismatches { get; set; }

        /// <summary>
        /// Diagnostics metadata such as adapter used, execution time,
        /// method name, module, correlation id, or stack traces.
        /// </summary>
        public Dictionary<string, object>? Diagnostics { get; set; }

        /// <summary>
        /// Correlation ID from the UPS envelope for end-to-end tracing.
        /// </summary>
        public string? CorrelationId { get; set; }

        // --------------------------------------------------------------------
        // Factory Methods (Success)
        // --------------------------------------------------------------------

        public static DispatcherResult FromSuccess(
            List<UParam> payload,
            string? correlationId = null,
            Dictionary<string, object>? diagnostics = null)
        {
            return new DispatcherResult
            {
                Success = true,
                Payload = payload,
                Diagnostics = diagnostics,
                CorrelationId = correlationId
            };
        }

        public static DispatcherResult EmptySuccess(string? correlationId = null)
        {
            return new DispatcherResult
            {
                Success = true,
                Payload = new List<UParam>(),
                CorrelationId = correlationId
            };
        }

        // --------------------------------------------------------------------
        // Factory Methods (Errors)
        // --------------------------------------------------------------------

        public static DispatcherResult FromError(
            List<UParam> errorPayload,
            string errorType = "UnknownError",
            string? correlationId = null,
            List<ContractMismatchDetail>? mismatches = null,
            Dictionary<string, object>? diagnostics = null)
        {
            return new DispatcherResult
            {
                Success = false,
                Payload = errorPayload,
                ErrorType = errorType,
                CorrelationId = correlationId,
                Mismatches = mismatches,
                Diagnostics = diagnostics
            };
        }

        public static DispatcherResult FromContractError(
            ContractValidationResult validationResult,
            string moduleName,
            string methodName,
            string? correlationId = null)
        {
            var payload = validationResult.ToUPS(moduleName, methodName);

            return new DispatcherResult
            {
                Success = false,
                ErrorType = "ContractError",
                Payload = payload,
                CorrelationId = correlationId,
                Mismatches = validationResult.Mismatches,
                Diagnostics = new Dictionary<string, object>
                {
                    ["module"] = moduleName,
                    ["method"] = methodName,
                    ["errors"] = validationResult.Errors
                }
            };
        }

        public static DispatcherResult FromInvocationError(
            string moduleName,
            string methodName,
            string message,
            string? correlationId = null)
        {
            var payload = StandardUPSErrors.ContractError(
                moduleName,
                methodName,
                new List<string> { message });

            return new DispatcherResult
            {
                Success = false,
                ErrorType = "InvocationError",
                Payload = new List<UParam> { payload },
                CorrelationId = correlationId,
                Diagnostics = new Dictionary<string, object>
                {
                    ["module"] = moduleName,
                    ["method"] = methodName,
                    ["exception"] = message
                }
            };
        }
    }
}
