// <auto-generated />
using System;
using AVA.Memory.Sql.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AVA.Memory.Sql.Migrations
{
    [DbContext(typeof(MemoryDbContext))]
    [Migration("20251112195547_AddIdentityFields")]
    partial class AddIdentityFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AVA.Memory.Data.Entities.AssociationEdge", b =>
                {
                    b.Property<string>("ID")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FromRecordID")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)");

                    b.Property<byte[]>("IdentityList")
                        .HasColumnType("VARBINARY(MAX)");

                    b.Property<string>("PrimaryIdentityHandle")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PrimaryIdentityId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("PrimaryIdentityType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ToRecordID")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.HasIndex("FromRecordID");

                    b.HasIndex("ToRecordID");

                    b.ToTable("AssociationEdges");
                });

            modelBuilder.Entity("AVA.Memory.Data.Entities.MemoryMetadata", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("IdentityList")
                        .HasColumnType("VARBINARY(MAX)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("PrimaryIdentityHandle")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PrimaryIdentityId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("PrimaryIdentityType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("RecordID")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("RecordID", "Key")
                        .IsUnique();

                    b.ToTable("MemoryMetadata");
                });

            modelBuilder.Entity("AVA.Memory.Data.Entities.MemoryRecord", b =>
                {
                    b.Property<string>("ID")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ContextId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("DecayRate")
                        .HasColumnType("float");

                    b.Property<string>("EpisodeId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<double>("Frequency")
                        .HasColumnType("float");

                    b.Property<byte[]>("IdentityList")
                        .HasColumnType("VARBINARY(MAX)");

                    b.Property<DateTime>("LastAccessedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("Novelty")
                        .HasColumnType("float");

                    b.Property<string>("PrimaryIdentityHandle")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PrimaryIdentityId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("PrimaryIdentityType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<double>("Salience")
                        .HasColumnType("float");

                    b.Property<string>("Source")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Text")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("LastAccessedAt");

                    b.HasIndex("Salience");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("MemoryRecords");
                });

            modelBuilder.Entity("AVA.Memory.Data.Entities.MemoryTag", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("IdentityList")
                        .HasColumnType("VARBINARY(MAX)");

                    b.Property<string>("PrimaryIdentityHandle")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PrimaryIdentityId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("PrimaryIdentityType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("RecordID")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("RecordID", "Tag")
                        .IsUnique();

                    b.ToTable("MemoryTags");
                });

            modelBuilder.Entity("AVA.Memory.Data.Entities.MemoryVector", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("IdentityList")
                        .HasColumnType("VARBINARY(MAX)");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<string>("PrimaryIdentityHandle")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PrimaryIdentityId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("PrimaryIdentityType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("RecordID")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<float>("Value")
                        .HasColumnType("real");

                    b.HasKey("ID");

                    b.HasIndex("RecordID", "Index")
                        .IsUnique();

                    b.ToTable("MemoryVectors");
                });

            modelBuilder.Entity("AVA.Memory.Data.Entities.AssociationEdge", b =>
                {
                    b.HasOne("AVA.Memory.Data.Entities.MemoryRecord", "FromRecord")
                        .WithMany("OutgoingEdges")
                        .HasForeignKey("FromRecordID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AVA.Memory.Data.Entities.MemoryRecord", "ToRecord")
                        .WithMany("IncomingEdges")
                        .HasForeignKey("ToRecordID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromRecord");

                    b.Navigation("ToRecord");
                });

            modelBuilder.Entity("AVA.Memory.Data.Entities.MemoryMetadata", b =>
                {
                    b.HasOne("AVA.Memory.Data.Entities.MemoryRecord", "Record")
                        .WithMany("Metadata")
                        .HasForeignKey("RecordID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Record");
                });

            modelBuilder.Entity("AVA.Memory.Data.Entities.MemoryTag", b =>
                {
                    b.HasOne("AVA.Memory.Data.Entities.MemoryRecord", "Record")
                        .WithMany("Tags")
                        .HasForeignKey("RecordID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Record");
                });

            modelBuilder.Entity("AVA.Memory.Data.Entities.MemoryVector", b =>
                {
                    b.HasOne("AVA.Memory.Data.Entities.MemoryRecord", "Record")
                        .WithMany("Vectors")
                        .HasForeignKey("RecordID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Record");
                });

            modelBuilder.Entity("AVA.Memory.Data.Entities.MemoryRecord", b =>
                {
                    b.Navigation("IncomingEdges");

                    b.Navigation("Metadata");

                    b.Navigation("OutgoingEdges");

                    b.Navigation("Tags");

                    b.Navigation("Vectors");
                });
#pragma warning restore 612, 618
        }
    }
}
